# Generated by Django 4.2.11 on 2024-05-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('body', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='blogs/banner')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-pub_date'],
            },
        ),
    ]
